build: pin to compat. version of numpy
The numpy==2.5.0 release today (2026-06-21), triggers an unresolvable diamond dependency deadlock:
```
      RuntimeError: Cannot install on Python version 3.12.9; only versions >=3.6,<3.10 are supported.

hint: `numba` (v0.53.1) was included because `horde-engine[rembg]` depends on `rembg` (v2.0.76) which depends on `pymatting` (v1.1.14) which depends on `numba`
```